query {
  entrypoint {
    id
    name
    villageConnection {
      village{
        id
        name
        villageConnection {
          village {
            id
            name
          }
        }
      }
    }
  }
}